import { Entry } from './types'

const today = new Date()
const fmt = (d: Date) => d.toISOString().split('T')[0]
const daysAgo = (n: number) => {
  const d = new Date(today)
  d.setDate(d.getDate() - n)
  return fmt(d)
}
const daysAhead = (n: number) => {
  const d = new Date(today)
  d.setDate(d.getDate() + n)
  return fmt(d)
}

export const SEED_ENTRIES: Entry[] = [
  {
    id: 1,
    text: 'Received payment from Acme Corp for Q1 consulting',
    timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 9, 14).toISOString(),
    actionDate: null,
    tags: ['consulting', 'payment'],
    folder: 'Clients/Acme Corp',
    amount: 4500,
    amountType: 'inflow',
    entity: 'Acme Corp',
    timeLogs: [],
  },
  {
    id: 2,
    text: 'Paid AWS invoice for March hosting',
    timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 10, 32).toISOString(),
    actionDate: null,
    tags: ['infrastructure', 'cloud'],
    folder: 'Expenses/SaaS',
    amount: 312,
    amountType: 'outflow',
    entity: 'AWS',
    timeLogs: [],
  },
  {
    id: 3,
    text: 'Call with Sarah about product roadmap — follow up on pricing',
    timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 11, 5).toISOString(),
    actionDate: daysAhead(2),
    tags: ['meeting', 'product'],
    folder: null,
    amount: null,
    amountType: null,
    entity: 'Sarah',
    timeLogs: [],
  },
  {
    id: 4,
    text: 'Subscribed to Figma team plan renewal',
    timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 14, 21).toISOString(),
    actionDate: null,
    tags: ['design', 'saas'],
    folder: 'Expenses/SaaS',
    amount: 45,
    amountType: 'outflow',
    entity: 'Figma',
    timeLogs: [],
  },
  {
    id: 5,
    text: 'Sent invoice #112 to Beta Solutions for web dev work',
    timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 15, 47).toISOString(),
    actionDate: daysAhead(7),
    tags: ['invoice', 'webdev'],
    folder: 'Clients/Beta Solutions',
    amount: 2800,
    amountType: 'inflow',
    entity: 'Beta Solutions',
    timeLogs: [],
  },
  {
    id: 6,
    text: 'Follow up with Ravi on the contract draft',
    timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 16, 3).toISOString(),
    actionDate: fmt(today),
    tags: ['legal', 'contract'],
    folder: null,
    amount: null,
    amountType: null,
    entity: 'Ravi',
    timeLogs: [],
  },
  {
    id: 7,
    text: 'Team lunch — split bill with design team',
    timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1, 13, 10).toISOString(),
    actionDate: null,
    tags: ['team', 'lunch'],
    folder: 'Expenses/Meals',
    amount: 180,
    amountType: 'outflow',
    entity: null,
    timeLogs: [],
  },
  {
    id: 8,
    text: 'Received deposit from Gamma Inc — project kickoff',
    timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1, 9, 45).toISOString(),
    actionDate: fmt(today),
    tags: ['kickoff', 'project'],
    folder: 'Clients/Gamma Inc',
    amount: 1500,
    amountType: 'inflow',
    entity: 'Gamma Inc',
    timeLogs: [],
  },
  {
    id: 9,
    text: 'Review and sign vendor agreement with TechParts Ltd',
    timestamp: daysAgo(10) + 'T09:00:00',
    actionDate: daysAgo(3),
    tags: ['legal', 'vendor'],
    folder: null,
    amount: null,
    amountType: null,
    entity: 'TechParts Ltd',
    timeLogs: [],
  },
  {
    id: 10,
    text: 'Send revised proposal to Metro Agency',
    timestamp: daysAgo(8) + 'T11:30:00',
    actionDate: daysAgo(2),
    tags: ['proposal', 'sales'],
    folder: null,
    amount: 6200,
    amountType: 'inflow',
    entity: 'Metro Agency',
    timeLogs: [],
  },
  {
    id: 11,
    text: 'Reconcile expense reports for Q1',
    timestamp: daysAgo(5) + 'T14:00:00',
    actionDate: daysAgo(1),
    tags: ['accounting', 'quarterly'],
    folder: 'Finance/Reporting',
    amount: null,
    amountType: null,
    entity: null,
    timeLogs: [],
  },
  {
    id: 12,
    text: 'Interesting idea: build a client dashboard for tracking invoices',
    timestamp: daysAgo(2) + 'T16:20:00',
    actionDate: null,
    tags: ['idea', 'product'],
    folder: null,
    amount: null,
    amountType: null,
    entity: null,
    timeLogs: [],
  },
  {
    id: 13,
    text: 'Check tax liability estimate before end of quarter',
    timestamp: daysAgo(3) + 'T10:00:00',
    actionDate: null,
    tags: ['tax', 'finance'],
    folder: 'Finance/Tax',
    amount: null,
    amountType: null,
    entity: null,
    timeLogs: [],
  },
  {
    id: 14,
    text: 'Travel to Bangalore for client meeting — flight booked',
    timestamp: daysAgo(1) + 'T08:00:00',
    actionDate: daysAhead(3),
    tags: ['travel', 'client'],
    folder: 'Expenses/Travel',
    amount: 8200,
    amountType: 'outflow',
    entity: 'IndiGo',
    timeLogs: [],
  },
]
